robot:
  type: ur5e_pgi
  action_mode: joint
  robot_ip: 192.168.1.5
  gripper_ip: 192.168.1.7
  gripper_port: 8887
  cameras:
    global:
      type: opencv
      index_or_path: /dev/video18
      width: 640
      height: 480
      fps: 20
    wrist:
      type: intelrealsense
      serial_number_or_name: "939622075456"
      width: 640
      height: 480
      fps: 20

teleop:
  type: gello_leader
  id: right_gello
  port: /dev/ttyUSB0

dataset:
  repo_id: FANYECHEN/ur5e-single-gello
  root: data/ur5e-single-gello
  num_episodes: 50
  fps: 20
  single_task: Place the banana and the red pepper into the orange tray.
  streaming_encoding: true
  push_to_hub: false

manual_episode_control: true
# resume: true
display_data: false
